### ISSUE TITLE
The transaction has been declined

### ISSUE THREAD

**Issue by sanjaykesari** [BluePay/BluePay_Payment_M2#12]
Getting error on checkout "The transaction has been declined" with magento2.2.4
Please help me

![error](https://user-images.githubusercontent.com/6104198/41529887-20d39fa8-730c-11e8-8a48-17226c60d8d9.png)

**Comment by ericmargules** [comment]
Hi @sanjaykesari,

Can you please contact your BluePay Merchant Services support. A transaction being declined is not usually a result of the Magento plugin. Instead it's usually the bank of the card you're trying to run. If you are in TEST mode, please remember that even dollar amounts will result in a decline (e.g. $20.17 will be declined), while odd dollar amounts will be approved (e.g. $13.20 will be approved).

**Comment by sanjaykesari** [comment]
Solved!! Thanks Guys :)
