### ISSUE TITLE
Missing cc_num without Checkout Iframe

### ISSUE THREAD

**Issue by hivikas** [BluePay/BluePay_Payment_M2#16]
Hello, 
We are getting error "Missing cc_num if we are set "Enable Checkout Iframe" no.We edit some files also for resolved that issue but din't get any success. 
Updated files are :- 
frontend/web/jspayment.js (add trim in line 146 and 153)
model/payment.php (add trim in line 895)
model/observer/datasssignobserver(add trim in line 53,54 and 60)

Request Data :- 

array(39) { ["order_id"]=> string(10) "4600000161" ["mode"]=> string(4) "TEST" ["tps_hash_type"]=> string(6) "SHA512" ["merchant"]=> string(12) "100308205860" ["transaction_type"]=> string(4) "SALE" ["payment_type"]=> string(6) "CREDIT" ["responseversion"]=> string(1) "3" ["tamper_proof_seal"]=> string(128) "fd81de506b27a727010da4efa1aca514f544f10174d85115f5cfe62828993e27fd925b6d68cc470654d2b2bbbddd11a76f820528728971e8a7a36a2f94b92e8f" ["amount"]=> string(2) "37" ["AMOUNT_TAX"]=> string(0) "" ["LV2_ITEM_TAX_RATE"]=> string(2) "0%" ["LV2_ITEM_SHIPPING_AMOUNT"]=> float(15) ["LV2_ITEM_DISCOUNT_AMOUNT"]=> string(0) "" ["LV2_ITEM_TAX_ID"]=> string(0) "" ["LV2_ITEM_BUYER_NAME"]=> string(13) "Azhar chauhan" ["LV2_ITEM_SHIP_NAME"]=> string(13) "Azhar chauhan" ["LV2_ITEM_SHIP_ADDR1"]=> string(17) "6350 LBJ Fwy #256" ["LV2_ITEM_SHIP_CITY"]=> string(6) "Dallas" ["LV2_ITEM_SHIP_STATE"]=> string(5) "Texas" ["LV2_ITEM_SHIP_ZIP"]=> string(0) "" ["LV2_ITEM_SHIP_COUNTRY"]=> string(2) "US" ["CUSTOMER_IP"]=> string(13) "203.122.57.34" ["company_name"]=> string(4) "1966" ["city"]=> string(6) "Dallas" ["state"]=> string(5) "Texas" ["zipcode"]=> string(5) "75240" ["country"]=> NULL ["phone"]=> string(10) "8055551212" ["fax"]=> NULL ["custom_id"]=> NULL ["comment"]=> string(0) "" ["email"]=> string(23) "test1212@mailinator.com" ["name1"]=> string(5) "Azhar" ["name2"]=> string(7) "chauhan" ["addr1"]=> string(17) "6350 LBJ Fwy #256" ["addr2"]=> string(0) "" ["cc_num"]=> string(16) "xxxxxxxxxxxx1881" ["cc_expires"]=> string(4) "0322" ["CVCCVV2"]=> string(3) "123" } 

Response :- object(BluePay\Payment\Model\Response)#3214 (1) { ["_data":protected]=> array(14) { ["result"]=> string(7) "MISSING" ["invoice_id"]=> string(0) "" ["bank_name"]=> string(0) "" ["message"]=> string(14) "Missing CC_NUM" ["auth_code"]=> string(0) "" ["avs"]=> string(0) "" ["rrno"]=> string(0) "" ["amount"]=> string(2) "37" ["payment_type"]=> string(6) "CREDIT" ["order_id"]=> string(10) "4600000161" ["cvv_2"]=> string(0) "" ["payment_account_mask"]=> string(0) "" ["cc_expires"]=> string(4) "0322" ["card_type"]=> string(0) "" } }

**Comment by ericmargules** [comment]
Hi, @hivikas. Have you updated to the most recent version of this plugin? Just to be clear, was the missing credit card number error coming before or after you made the edits? Also, can you please contact integration support? They'll be able to get more specifics on your situation .

**Comment by ericmargules** [comment]
Hi @hivikas. SALE transactions do not require RRNO. [See the API docs here](https://www.bluepay.com/sites/default/files/documentation/BluePay_bp10emu/BluePay%201-0%20Emulator.txt). Only CAPTURE, REFUND, and REBCANCEL require RRNO in the request.

Have you spoken with Integrations Support yet?

**Comment by hivikas** [comment]
Hello @ericmargules :- Issue resolved. I updated some files :- 

Space issue in card last 4 digits 

app/code/BluePay/Payment/view/frontend/web/js/view/payment/payment-form.js
Add trim inline no 146($("#bluepay_payment_cc_number").val(acct.label.substring(0, acct.label.indexOf('-')).trim()););
Add trim in line no 152(creditCardData.creditCardNumber = acct.label.substring(0, acct.label.indexOf('-')).trim(););

app/code/BluePay/Payment/Model/payment.php
Add code in line no 425(if($request->getRrno() == Null){ if(count($payment->getAdditionalInformation())){ $additionalInformation = $payment->getAdditionalInformation(); if(isset($additionalInformation['token'])){ $request->setRrno($additionalInformation['token']); $payment->setRrno($additionalInformation['token']); } } });
Add trim inline no 565($result->setCcNumber(trim($info->getCcNumber())););
Add trim inline no 580($result->setCcNumber(trim($info->getAdditionalInformation('cc_number'))););
Add trim inline no 908($infoInstance->setAdditionalInformation('cc_number', trim($infoInstance->getCcNumber())););


app/code/BluePay/Payment/Model/Observer/DataAssignObserver.php
Changes in line no 52 , 54,55 and 61
$ccNumber = trim($additionalData->getData('cc_number')); line no 52
$payment->setCcLast4(substr($ccNumber, -4)); line no 54
$payment->setCcNumber($ccNumber); line no 55
$payment->setCcNumber($ccNumber);line no 61
