### ISSUE TITLE
Upgrade Process

### ISSUE THREAD

**Issue by donovandb** [BluePay/BluePay_Payment_M2#9]
I'm trying to address an issue where bluepay is debited, but a magento order is not created. My first solution is to upgrade, since there looks to be some relative commits since my install in mid-december 2017. 

Magento 2.2.1

Is there a recommended upgrade process for this plug-in?

**Comment by cypher909** [comment]
I am having the same issue.

**Comment by ericmargules** [comment]
Hi @donovandb  and @cypher909,

Can you give us any more information about what is occurring when a purchase is created? Does Magento receive a response from BluePay with a Missing SHPF_FORM_ID error by chance?

**Comment by cypher909** [comment]
I wish I could but so far I haven't been able to reproduce the error. All I have to go on at the moment is reports from our customers.

**Comment by ericmargules** [comment]
@donovandb and @cypher909 We think we've resolved this issue. Sorry that it's taken so long to get back to you both about it. Please let me know if you experience this bug again in the future!

Thanks
